# Generated by Django 4.2.1 on 2023-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='water_tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms', models.CharField(blank=True, max_length=300, null=True)),
                ('pump_status', models.CharField(blank=True, max_length=300, null=True)),
                ('cumulative_lpd', models.CharField(blank=True, max_length=300, null=True)),
                ('current_lpm', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage', models.CharField(blank=True, max_length=300, null=True)),
                ('current', models.CharField(blank=True, max_length=300, null=True)),
                ('power', models.CharField(blank=True, max_length=300, null=True)),
                ('start_time', models.CharField(blank=True, max_length=300, null=True)),
                ('stop_time', models.CharField(blank=True, max_length=300, null=True)),
                ('run_time_today', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('district', models.CharField(blank=True, max_length=300, null=True)),
                ('size_of_the_system', models.CharField(blank=True, max_length=300, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=300, null=True)),
                ('contractor_number', models.CharField(blank=True, max_length=300, null=True)),
                ('serial_numbers', models.CharField(blank=True, max_length=300, null=True)),
                ('wattage', models.CharField(blank=True, max_length=300, null=True)),
                ('no_of_panels', models.CharField(blank=True, max_length=300, null=True)),
                ('installation_date', models.CharField(blank=True, max_length=300, null=True)),
                ('capacity', models.CharField(blank=True, max_length=300, null=True)),
                ('imei', models.CharField(blank=True, max_length=300, null=True)),
                ('ratings', models.CharField(blank=True, max_length=300, null=True)),
                ('model_number', models.CharField(blank=True, max_length=300, null=True)),
                ('fault', models.CharField(blank=True, max_length=300, null=True)),
                ('reported_on', models.CharField(blank=True, max_length=300, null=True)),
                ('attended_on', models.CharField(blank=True, max_length=300, null=True)),
                ('current_status', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
