# Generated by Django 4.2.1 on 2023-05-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='water_tank_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=300, null=True)),
                ('stop_time', models.CharField(blank=True, max_length=300, null=True)),
                ('run_time_today', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='run_time_today',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='stop_time',
        ),
    ]
