# Generated by Django 4.2.1 on 2023-05-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_water_tank_times_remove_water_tank_run_time_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank_times',
            name='rms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
