# Generated by Django 4.1.5 on 2023-08-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_water_tank_times_rms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water_tank_times',
            name='run_time_today',
        ),
        migrations.RemoveField(
            model_name='water_tank_times',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='water_tank_times',
            name='stop_time',
        ),
        migrations.AddField(
            model_name='water_tank',
            name='run_time_today',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='water_tank',
            name='start_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='water_tank',
            name='stop_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
