# Generated by Django 4.1.5 on 2023-08-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_remove_water_tank_times_run_time_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank',
            name='benificery_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
