# Generated by Django 4.1.5 on 2023-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_water_tank_benificery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_tank',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank',
            name='stop_time',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
    ]
