# Generated by Django 4.1.5 on 2023-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_alter_water_tank_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank',
            name='signal_strength',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
