# Generated by Django 4.1.5 on 2023-08-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_water_tank_signal_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='water_tank_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms', models.CharField(blank=True, max_length=300, null=True)),
                ('cumulative_lpd', models.CharField(blank=True, max_length=300, null=True)),
                ('current_lpm', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage', models.CharField(blank=True, max_length=300, null=True)),
                ('current', models.CharField(blank=True, max_length=300, null=True)),
                ('power', models.CharField(blank=True, max_length=300, null=True)),
                ('wattage', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='water_tank_times',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='cumulative_lpd',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='current',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='current_lpm',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='power',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='voltage',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='wattage',
        ),
    ]
