# Generated by Django 4.1.5 on 2023-08-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_water_tank_records_delete_water_tank_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank_records',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water_tank_records',
            name='stop_time',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
    ]
