# Generated by Django 4.1.5 on 2023-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_water_tank_records_present_lpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_tank_records',
            name='cumulative_lpd',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records',
            name='current',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records',
            name='current_lpm',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records',
            name='power',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records',
            name='present_lpm',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records',
            name='voltage',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records',
            name='wattage',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
