# Generated by Django 4.1.5 on 2023-08-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_alter_water_tank_records_cumulative_lpd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='water_tank_records_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms', models.CharField(blank=True, max_length=300, null=True)),
                ('cumulative_lpd', models.FloatField(blank=True, max_length=300, null=True)),
                ('current_lpm', models.FloatField(blank=True, max_length=300, null=True)),
                ('voltage', models.FloatField(blank=True, max_length=300, null=True)),
                ('current', models.FloatField(blank=True, max_length=300, null=True)),
                ('power', models.FloatField(blank=True, max_length=300, null=True)),
                ('wattage', models.FloatField(blank=True, max_length=300, null=True)),
                ('present_lpm', models.FloatField(blank=True, max_length=300, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('stop_time', models.TimeField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
