# Generated by Django 4.1.5 on 2023-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0015_water_tank_records_time_water_tank_records_temp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank_records',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='water_tank_records_temp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
