# Generated by Django 4.1.5 on 2023-08-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0016_water_tank_records_date_water_tank_records_temp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank',
            name='signal_strength',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
