# Generated by Django 4.1.5 on 2023-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_water_tank_signal_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank',
            name='date_of_installation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
