# Generated by Django 4.1.5 on 2023-08-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_water_tank_date_of_installation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water_tank',
            old_name='attended_on',
            new_name='controller_model_number',
        ),
        migrations.RenameField(
            model_name='water_tank',
            old_name='current_status',
            new_name='controller_serial_numbers',
        ),
        migrations.RenameField(
            model_name='water_tank',
            old_name='date_of_installation',
            new_name='iccid',
        ),
        migrations.RenameField(
            model_name='water_tank',
            old_name='fault',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='water_tank',
            old_name='imei',
            new_name='modem_id',
        ),
        migrations.RenameField(
            model_name='water_tank',
            old_name='model_number',
            new_name='pump_model_number',
        ),
        migrations.RenameField(
            model_name='water_tank',
            old_name='no_of_panels',
            new_name='pump_serial_numbers',
        ),
        migrations.RenameField(
            model_name='water_tank',
            old_name='ratings',
            new_name='sim_id',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='reported_on',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='serial_numbers',
        ),
        migrations.RemoveField(
            model_name='water_tank',
            name='size_of_the_system',
        ),
    ]
