# Generated by Django 4.1.5 on 2023-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0019_rename_attended_on_water_tank_controller_model_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank',
            name='site_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
