# Generated by Django 4.1.5 on 2023-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0023_alter_water_tank_records_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank',
            name='head',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
