# Generated by Django 4.1.5 on 2023-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0024_water_tank_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_tank',
            name='pump_status',
            field=models.CharField(blank=True, default='OF', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records',
            name='run_time_today',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records_temp',
            name='run_time_today',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
