# Generated by Django 4.1.5 on 2023-11-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0026_alter_water_tank_rms_alter_water_tank_records_rms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water_tank',
            name='latitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='water_tank',
            name='longitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
