# Generated by Django 4.1.5 on 2023-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0027_water_tank_latitude_water_tank_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water_tank_records',
            name='rms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='water_tank_records_temp',
            name='rms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
